<?php

/**
 * Implementation of hook_views_api().
 */
function koken_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'koken') . '/includes/views',
  );
}

/**
 * Initialize a new Koken object.
 *
 * @param $url
 *   the url of a Koken install.
 * @return bool|Koken
 */
function koken_initialize_library($url) {
  if (empty($url)) {
    return FALSE;
  }
  return new Koken($url);
}
