<?php

/**
 * @file
 * Allow to requests a koken install using views.
 */

/**
 * Implements hook_views_api().
 */
function koken_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'koken') . '/includes/views',
  );
}

/**
 * Initialize a new Koken object.
 *
 * @param string $url
 *   the url of a Koken install.
 *
 * @return bool|Koken
 *   A Koken object, used to query against the rest API with curl.
 */
function koken_initialize_library($url) {
  if (empty($url)) {
    return FALSE;
  }
  return new Koken($url);
}
